
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.text.DefaultCaret;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author proto
 */
public class RPGMainJFram extends javax.swing.JFrame {

   

    /**
     * Creates new form RPGMainJFram
     */
    public RPGMainJFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuLook = new javax.swing.JPopupMenu();
        menuCharacter = new javax.swing.JMenuItem();
        menuRoom = new javax.swing.JMenuItem();
        jPopupMenuMove = new javax.swing.JPopupMenu();
        jPopupMenuGet = new javax.swing.JPopupMenu();
        jPopupMenuFight = new javax.swing.JPopupMenu();
        jPanelOutput = new javax.swing.JPanel();
        jScrollPaneOutput = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jPanelActionBar = new javax.swing.JPanel();
        jButtonLook = new javax.swing.JButton();
        jButtonMove = new javax.swing.JButton();
        jButtonFight = new javax.swing.JButton();
        jButtonGet = new javax.swing.JButton();
        jLabelHP = new javax.swing.JLabel();
        jLabelAcc = new javax.swing.JLabel();
        jLabelRoom = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelHPNum = new javax.swing.JLabel();
        jLabelAccNum = new javax.swing.JLabel();
        jLabelRoomNum = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        menuCharacter.setText("Character");
        menuCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCharacterActionPerformed(evt);
            }
        });
        jPopupMenuLook.add(menuCharacter);

        menuRoom.setText("Room");
        menuRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRoomActionPerformed(evt);
            }
        });
        jPopupMenuLook.add(menuRoom);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jScrollPaneOutput.setAutoscrolls(true);

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPaneOutput.setViewportView(jTextAreaOutput);

        javax.swing.GroupLayout jPanelOutputLayout = new javax.swing.GroupLayout(jPanelOutput);
        jPanelOutput.setLayout(jPanelOutputLayout);
        jPanelOutputLayout.setHorizontalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneOutput)
        );
        jPanelOutputLayout.setVerticalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jPanelActionBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonLook.setText("Look");
        jButtonLook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLookMouseClicked(evt);
            }
        });
        jButtonLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLookActionPerformed(evt);
            }
        });

        jButtonMove.setText("Move");
        jButtonMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMoveMouseClicked(evt);
            }
        });

        jButtonFight.setText("Fight");
        jButtonFight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFightMouseClicked(evt);
            }
        });

        jButtonGet.setText("Get");
        jButtonGet.setMaximumSize(new java.awt.Dimension(59, 25));
        jButtonGet.setMinimumSize(new java.awt.Dimension(59, 25));
        jButtonGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetActionPerformed(evt);
            }
        });

        jLabelHP.setText("Health Points: ");

        jLabelAcc.setText("Accuracy: ");

        jLabelRoom.setText("Room: ");

        jLabelHPNum.setPreferredSize(new java.awt.Dimension(50, 25));

        jButton1.setText("Equip");

        jButton2.setText("Remove");

        javax.swing.GroupLayout jPanelActionBarLayout = new javax.swing.GroupLayout(jPanelActionBar);
        jPanelActionBar.setLayout(jPanelActionBarLayout);
        jPanelActionBarLayout.setHorizontalGroup(
            jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFight)
                    .addComponent(jButtonMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(175, 175, 175)
                .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addComponent(jLabelRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRoomNum))
                    .addComponent(jLabelName)
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addComponent(jLabelAcc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAccNum))
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addComponent(jLabelHP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHPNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(163, 163, 163)
                .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelActionBarLayout.setVerticalGroup(
            jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLook)
                            .addComponent(jButtonGet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                                .addComponent(jButtonMove)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFight))
                            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))))
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelName)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelHPNum, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabelHP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAcc)
                            .addComponent(jLabelAccNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRoom)
                            .addComponent(jLabelRoomNum))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelActionBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelActionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLookMouseClicked
        // TODO add your handliadsdasng code here:dsfsdf
        jPopupMenuLook.show((Component)evt.getSource(), 0, 0);
        
    }//GEN-LAST:event_jButtonLookMouseClicked

    private void jButtonMoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMoveMouseClicked
        // TODO add your handling code here:
       jPopupMenuMove.show((Component)evt.getSource(), 0, 0);
    }//GEN-LAST:event_jButtonMoveMouseClicked

    private void jButtonFightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFightMouseClicked
        // TODO add your handling code here:
        jPopupMenuFight.show((Component)evt.getSource(), 0, 0);
    }//GEN-LAST:event_jButtonFightMouseClicked

    private void jButtonLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLookActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //System.out.println("hehe haha");
    }//GEN-LAST:event_formMouseClicked

    private void menuRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRoomActionPerformed
        // TODO add your handling code here:
        String[] x = new String[]{"look"};
        gameLogic.look(x);
    }//GEN-LAST:event_menuRoomActionPerformed

    private void menuCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCharacterActionPerformed
        // TODO add your handling code here:
        String[] x = new String[]{"look", "self"};
        gameLogic.look(x);
    }//GEN-LAST:event_menuCharacterActionPerformed

    private void jButtonGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetActionPerformed
        // TODO add your handling code here:
        jPopupMenuGet.show((Component)evt.getSource(), 0, 0);
    }//GEN-LAST:event_jButtonGetActionPerformed
    public static void updateRoom(){
    while(jPopupMenuMove.getSubElements().length != 0) jPopupMenuMove.remove(0);
    while(jPopupMenuLook.getSubElements().length != 2) jPopupMenuLook.remove(2);
    while(jPopupMenuFight.getSubElements().length != 0) jPopupMenuFight.remove(0);
    while(jPopupMenuGet.getSubElements().length != 0) jPopupMenuGet.remove(0);

    Room currentRoom = null; // <-- I had to do this and I dont know why, netBeans being netBeans.
    for (Room room : Objects.room){
        if (room.number == Objects.player.inRoom) currentRoom = room;
    }
    jLabelRoomNum.setText(currentRoom.name);
    for (Item item : currentRoom.item){
        JMenuItem getItem = jPopupMenuGet.add(item.name);
        getItem.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent ev) {
                    String[] x = new String[]{"get", getItem.getText()};
                    gameLogic.get(x);
                }
            });
    }
    for (String room : currentRoom.doors){
        JMenuItem roomItem = jPopupMenuMove.add(room.split(" ")[1]);
                roomItem.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent ev) {
                    String[] x = new String[]{"move", roomItem.getText()};
                    gameLogic.move(x);
                }
            });
    }
    for (NPC npc : currentRoom.npc){
        //jPopupMenuLook
        JMenuItem npcItem = new JMenuItem(npc.id);
        npcItem.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent ev) {
                    String[] x = new String[]{"look", npcItem.getText()};
                    gameLogic.look(x);
                }
            });
            jPopupMenuLook.add(npcItem);
            JMenuItem fightItem = jPopupMenuFight.add(npc.name);
            fightItem.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent ev) {
                    String[] x = new String[]{"fight", fightItem.getText()};
                    Objects.combat.fight(x);
                }
            });
        }
    }

    static Logic gameLogic = new Logic();
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPGMainJFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RPGMainJFram().setVisible(true);
            PrintStream out = new PrintStream(new OutputStream() {
                @Override
                public void write(int b) throws IOException {
                    jTextAreaOutput.append("" + (char) (b & 0xFF));
                }
            });
            System.setOut(out);
            Thread thread = new Thread() {
                @Override
                public void run() {
                   DefaultCaret caret = (DefaultCaret)jTextAreaOutput.getCaret();
                    caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
                    Objects.setupNPCArray();
                    Objects.setupItemArray();
                    itemThreading threads = new itemThreading(gameLogic);
                    threads.itemThread();
                    npcThreading thread = new npcThreading(gameLogic);
                    thread.npcThread();
                    gameLogic.inputCommand();
                }
            };
            thread.start();
        });
    
                
              
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFight;
    private javax.swing.JButton jButtonGet;
    private javax.swing.JButton jButtonLook;
    private javax.swing.JButton jButtonMove;
    public javax.swing.JLabel jLabelAcc;
    public static javax.swing.JLabel jLabelAccNum;
    public javax.swing.JLabel jLabelHP;
    public static javax.swing.JLabel jLabelHPNum;
    public static javax.swing.JLabel jLabelName;
    public javax.swing.JLabel jLabelRoom;
    public static javax.swing.JLabel jLabelRoomNum;
    private javax.swing.JPanel jPanelActionBar;
    private javax.swing.JPanel jPanelOutput;
    private static javax.swing.JPopupMenu jPopupMenuFight;
    private static javax.swing.JPopupMenu jPopupMenuGet;
    private static javax.swing.JPopupMenu jPopupMenuLook;
    private static javax.swing.JPopupMenu jPopupMenuMove;
    private javax.swing.JScrollPane jScrollPaneOutput;
    private static javax.swing.JTextArea jTextAreaOutput;
    private javax.swing.JMenuItem menuCharacter;
    private javax.swing.JMenuItem menuRoom;
    // End of variables declaration//GEN-END:variables

    private static class jPanelActionBar {

        public jPanelActionBar() {
        }

        private void revalidate() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
