
import java.awt.Container;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author proto
 */
public class RPGMainJFram extends javax.swing.JFrame {

   

    /**
     * Creates new form RPGMainJFram
     */
    public RPGMainJFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuLook = new javax.swing.JPopupMenu();
        Room = new javax.swing.JMenuItem();
        Character = new javax.swing.JMenuItem();
        jPopupMenuMove = new javax.swing.JPopupMenu();
        jPopupMenuInv = new javax.swing.JPopupMenu();
        Get = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanelOutput = new javax.swing.JPanel();
        jScrollPaneOutput = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jPanelActionBar = new javax.swing.JPanel();
        jButtonLook = new javax.swing.JButton();
        jButtonMove = new javax.swing.JButton();
        jButtonGet = new javax.swing.JButton();
        jButtonFight = new javax.swing.JButton();
        jLabelHP = new javax.swing.JLabel();
        jLabelAcc = new javax.swing.JLabel();
        jLabelRoom = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelHPNum = new javax.swing.JLabel();
        jLabelAccNum = new javax.swing.JLabel();
        jLabelRoomNum = new javax.swing.JLabel();

        Room.setText("Room");
        jPopupMenuLook.add(Room);

        Character.setText("Character");
        jPopupMenuLook.add(Character);

        Get.setText("jMenuItem1");
        jPopupMenuInv.add(Get);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPaneOutput.setViewportView(jTextAreaOutput);

        javax.swing.GroupLayout jPanelOutputLayout = new javax.swing.GroupLayout(jPanelOutput);
        jPanelOutput.setLayout(jPanelOutputLayout);
        jPanelOutputLayout.setHorizontalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneOutput)
        );
        jPanelOutputLayout.setVerticalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jPanelActionBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonLook.setText("Look");
        jButtonLook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLookMouseClicked(evt);
            }
        });
        jButtonLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLookActionPerformed(evt);
            }
        });

        jButtonMove.setText("Move");
        jButtonMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMoveMouseClicked(evt);
            }
        });

        jButtonGet.setText("Inventory");
        jButtonGet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGetMouseClicked(evt);
            }
        });

        jButtonFight.setText("Fight");
        jButtonFight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFightMouseClicked(evt);
            }
        });

        jLabelHP.setText("Health Points: ");

        jLabelAcc.setText("Accuracy: ");

        jLabelRoom.setText("Room: ");

        javax.swing.GroupLayout jPanelActionBarLayout = new javax.swing.GroupLayout(jPanelActionBar);
        jPanelActionBar.setLayout(jPanelActionBarLayout);
        jPanelActionBarLayout.setHorizontalGroup(
            jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLook)
                .addGap(18, 18, 18)
                .addComponent(jButtonMove)
                .addGap(18, 18, 18)
                .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                                .addComponent(jLabelAcc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAccNum))
                            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                                .addComponent(jLabelHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelHPNum)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jButtonGet)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFight))
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                                .addComponent(jLabelRoom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRoomNum)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelActionBarLayout.setVerticalGroup(
            jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionBarLayout.createSequentialGroup()
                .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionBarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLook)
                            .addComponent(jButtonMove)
                            .addComponent(jButtonGet)
                            .addComponent(jButtonFight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActionBarLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHP)
                            .addComponent(jLabelHPNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAcc)
                            .addComponent(jLabelAccNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoom)
                    .addComponent(jLabelRoomNum))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelActionBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelActionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLookMouseClicked
        // TODO add your handliadsdasng code here:dsfsdf
        jPopupMenuLook.show(this, 70, 330);
        
    }//GEN-LAST:event_jButtonLookMouseClicked

    private void jButtonMoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMoveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMoveMouseClicked

    private void jButtonFightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFightMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFightMouseClicked

    private void jButtonGetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGetMouseClicked

    private void jButtonLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLookActionPerformed

    /**
     * @param args the command line arguments
     */
    static Logic gameLogic = new Logic();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPGMainJFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RPGMainJFram().setVisible(true);
            PrintStream out = new PrintStream(new OutputStream() {
                @Override
                public void write(int b) throws IOException {
                    jTextAreaOutput.append("" + (char) (b & 0xFF));
                }
            });
            System.setOut(out);
            Thread thread = new Thread() {
                @Override
                public void run() {
                    Objects.setupNPCArray();
                    Objects.setupItemArray();
                    itemThreading threads = new itemThreading(gameLogic);
                    threads.itemThread();
                    npcThreading thread = new npcThreading(gameLogic);
                    thread.npcThread();
                    gameLogic.inputCommand();
                }
            };
            thread.start();
        });
                //jLabelHP.setText( String.valueOf(Objects.player.hp) );
                //jLabelHP.setText( Objects.player.hp  + "" );
                
              
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Character;
    private javax.swing.JMenuItem Get;
    private javax.swing.JMenuItem Room;
    private javax.swing.JButton jButtonFight;
    private javax.swing.JButton jButtonGet;
    private javax.swing.JButton jButtonLook;
    private javax.swing.JButton jButtonMove;
    public javax.swing.JLabel jLabelAcc;
    public static javax.swing.JLabel jLabelAccNum;
    public javax.swing.JLabel jLabelHP;
    public static javax.swing.JLabel jLabelHPNum;
    public static javax.swing.JLabel jLabelName;
    public javax.swing.JLabel jLabelRoom;
    public static javax.swing.JLabel jLabelRoomNum;
    private javax.swing.JPanel jPanelActionBar;
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenuInv;
    private javax.swing.JPopupMenu jPopupMenuLook;
    private javax.swing.JPopupMenu jPopupMenuMove;
    private javax.swing.JScrollPane jScrollPaneOutput;
    private static javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables

    private static class jPanelActionBar {

        public jPanelActionBar() {
        }

        private void revalidate() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
